-- Marques rangées par ligne commerciale.
--
-- Une marque du catalogue = la ligne telle que le client la nomme : Giorgio Armani, Emporio Armani
-- et Armani Privé sont trois gammes (flacon, prix, nom demandé en boutique) ; de même Dior et
-- La Collection Privée Christian Dior, Tom Ford et Tom Ford Private Blend, etc. Le catalogue les
-- mélangeait sous la marque mère (« Emporio Armani Stronger With You » rangé chez Giorgio Armani,
-- Gris Dior chez Dior). La découpe est celle du référentiel de recherche
-- (`src/lib/search/reference/data/*.json`) : un parfum quitte sa marque mère seulement si le
-- référentiel le range dans une ligne de cette marque.
--
-- Cette migration ne FUSIONNE ni ne SUPPRIME rien :
--   · elle crée la marque de ligne si elle manque (CURATED, PUBLISHED, sans logo : à déposer depuis
--     la gestion), uniquement quand au moins un parfum doit y entrer — jamais de marque vide ;
--   · elle déplace les parfums reconnus et retire du nom le préfixe de ligne collé à la saisie
--     (« Emporio Armani Stronger With You Powerfully » → « Stronger With You Powerfully ») ;
--   · elle laisse intactes les marques mères (slug, logo, statut). Les adresses publiques
--     `/parfums/<marque>/<nom>-<id>` redirigent en 308 : l'identifiant fait foi.
-- Les lignes de vente gardent leur nom de marque d'origine (instantané, jamais réécrit).
-- Rejouée, elle ne trouve plus rien à déplacer. Deux parfums qui arriveraient sous le même nom dans
-- la même ligne : seul le plus ancien bouge, l'autre reste en place (doublon à trancher dans la
-- gestion).

BEGIN;

CREATE TEMP TABLE _deplacements (
  marque_source TEXT NOT NULL,
  parfum_source TEXT NOT NULL,
  marque_cible  TEXT NOT NULL,
  slug_cible    TEXT NOT NULL,
  nom_cible     TEXT NOT NULL
);

INSERT INTO _deplacements (marque_source, parfum_source, marque_cible, slug_cible, nom_cible) VALUES
  ('Giorgio Armani', 'Stronger With You', 'Emporio Armani', 'emporio-armani', 'Stronger With You'),
  ('Giorgio Armani', 'Emporio Armani Stronger With You', 'Emporio Armani', 'emporio-armani', 'Stronger With You'),
  ('Giorgio Armani', 'Emporio Stronger With You', 'Emporio Armani', 'emporio-armani', 'Stronger With You'),
  ('Giorgio Armani', 'Stronger With You Intensely', 'Emporio Armani', 'emporio-armani', 'Stronger With You Intensely'),
  ('Giorgio Armani', 'Emporio Armani Stronger With You Intensely', 'Emporio Armani', 'emporio-armani', 'Stronger With You Intensely'),
  ('Giorgio Armani', 'Emporio Stronger With You Intensely', 'Emporio Armani', 'emporio-armani', 'Stronger With You Intensely'),
  ('Giorgio Armani', 'Stronger With You Absolutely', 'Emporio Armani', 'emporio-armani', 'Stronger With You Absolutely'),
  ('Giorgio Armani', 'Emporio Armani Stronger With You Absolutely', 'Emporio Armani', 'emporio-armani', 'Stronger With You Absolutely'),
  ('Giorgio Armani', 'Emporio Stronger With You Absolutely', 'Emporio Armani', 'emporio-armani', 'Stronger With You Absolutely'),
  ('Giorgio Armani', 'Stronger With You Powerfully', 'Emporio Armani', 'emporio-armani', 'Stronger With You Powerfully'),
  ('Giorgio Armani', 'Emporio Armani Stronger With You Powerfully', 'Emporio Armani', 'emporio-armani', 'Stronger With You Powerfully'),
  ('Giorgio Armani', 'Emporio Stronger With You Powerfully', 'Emporio Armani', 'emporio-armani', 'Stronger With You Powerfully'),
  ('Giorgio Armani', 'Stronger With You Oud', 'Emporio Armani', 'emporio-armani', 'Stronger With You Oud'),
  ('Giorgio Armani', 'Emporio Armani Stronger With You Oud', 'Emporio Armani', 'emporio-armani', 'Stronger With You Oud'),
  ('Giorgio Armani', 'Emporio Stronger With You Oud', 'Emporio Armani', 'emporio-armani', 'Stronger With You Oud'),
  ('Giorgio Armani', 'Stronger With You Leather', 'Emporio Armani', 'emporio-armani', 'Stronger With You Leather'),
  ('Giorgio Armani', 'Emporio Armani Stronger With You Leather', 'Emporio Armani', 'emporio-armani', 'Stronger With You Leather'),
  ('Giorgio Armani', 'Emporio Stronger With You Leather', 'Emporio Armani', 'emporio-armani', 'Stronger With You Leather'),
  ('Giorgio Armani', 'Stronger With You Freeze', 'Emporio Armani', 'emporio-armani', 'Stronger With You Freeze'),
  ('Giorgio Armani', 'Emporio Armani Stronger With You Freeze', 'Emporio Armani', 'emporio-armani', 'Stronger With You Freeze'),
  ('Giorgio Armani', 'Emporio Stronger With You Freeze', 'Emporio Armani', 'emporio-armani', 'Stronger With You Freeze'),
  ('Giorgio Armani', 'Stronger With You Only', 'Emporio Armani', 'emporio-armani', 'Stronger With You Only'),
  ('Giorgio Armani', 'Emporio Armani Stronger With You Only', 'Emporio Armani', 'emporio-armani', 'Stronger With You Only'),
  ('Giorgio Armani', 'Emporio Stronger With You Only', 'Emporio Armani', 'emporio-armani', 'Stronger With You Only'),
  ('Giorgio Armani', 'Power of You', 'Emporio Armani', 'emporio-armani', 'Power of You'),
  ('Giorgio Armani', 'Emporio Armani Power of You', 'Emporio Armani', 'emporio-armani', 'Power of You'),
  ('Giorgio Armani', 'Emporio Power of You', 'Emporio Armani', 'emporio-armani', 'Power of You'),
  ('Giorgio Armani', 'Because It''s You', 'Emporio Armani', 'emporio-armani', 'Because It''s You'),
  ('Giorgio Armani', 'Emporio Armani Because It''s You', 'Emporio Armani', 'emporio-armani', 'Because It''s You'),
  ('Giorgio Armani', 'Emporio Because It''s You', 'Emporio Armani', 'emporio-armani', 'Because It''s You'),
  ('Giorgio Armani', 'In Love With You', 'Emporio Armani', 'emporio-armani', 'In Love With You'),
  ('Giorgio Armani', 'Emporio Armani In Love With You', 'Emporio Armani', 'emporio-armani', 'In Love With You'),
  ('Giorgio Armani', 'Emporio In Love With You', 'Emporio Armani', 'emporio-armani', 'In Love With You'),
  ('Giorgio Armani', 'Diamonds', 'Emporio Armani', 'emporio-armani', 'Diamonds'),
  ('Giorgio Armani', 'Emporio Armani Diamonds', 'Emporio Armani', 'emporio-armani', 'Diamonds'),
  ('Giorgio Armani', 'Emporio Diamonds', 'Emporio Armani', 'emporio-armani', 'Diamonds'),
  ('Giorgio Armani', 'Diamonds Intense', 'Emporio Armani', 'emporio-armani', 'Diamonds Intense'),
  ('Giorgio Armani', 'Emporio Armani Diamonds Intense', 'Emporio Armani', 'emporio-armani', 'Diamonds Intense'),
  ('Giorgio Armani', 'Emporio Diamonds Intense', 'Emporio Armani', 'emporio-armani', 'Diamonds Intense'),
  ('Giorgio Armani', 'Diamonds for Men', 'Emporio Armani', 'emporio-armani', 'Diamonds for Men'),
  ('Giorgio Armani', 'Emporio Armani Diamonds for Men', 'Emporio Armani', 'emporio-armani', 'Diamonds for Men'),
  ('Giorgio Armani', 'Emporio Diamonds for Men', 'Emporio Armani', 'emporio-armani', 'Diamonds for Men'),
  ('Giorgio Armani', 'He', 'Emporio Armani', 'emporio-armani', 'He'),
  ('Giorgio Armani', 'Emporio Armani He', 'Emporio Armani', 'emporio-armani', 'He'),
  ('Giorgio Armani', 'Emporio He', 'Emporio Armani', 'emporio-armani', 'He'),
  ('Giorgio Armani', 'She', 'Emporio Armani', 'emporio-armani', 'She'),
  ('Giorgio Armani', 'Emporio Armani She', 'Emporio Armani', 'emporio-armani', 'She'),
  ('Giorgio Armani', 'Emporio She', 'Emporio Armani', 'emporio-armani', 'She'),
  ('Giorgio Armani', 'City Glow', 'Emporio Armani', 'emporio-armani', 'City Glow'),
  ('Giorgio Armani', 'Emporio Armani City Glow', 'Emporio Armani', 'emporio-armani', 'City Glow'),
  ('Giorgio Armani', 'Emporio City Glow', 'Emporio Armani', 'emporio-armani', 'City Glow'),
  ('Giorgio Armani', 'Remix', 'Emporio Armani', 'emporio-armani', 'Remix'),
  ('Giorgio Armani', 'Emporio Armani Remix', 'Emporio Armani', 'emporio-armani', 'Remix'),
  ('Giorgio Armani', 'Emporio Remix', 'Emporio Armani', 'emporio-armani', 'Remix'),
  ('Giorgio Armani', 'White', 'Emporio Armani', 'emporio-armani', 'White'),
  ('Giorgio Armani', 'Emporio Armani White', 'Emporio Armani', 'emporio-armani', 'White'),
  ('Giorgio Armani', 'Emporio White', 'Emporio Armani', 'emporio-armani', 'White'),
  ('Giorgio Armani', 'Rose d''Arabie', 'Armani Privé', 'armani-prive', 'Rose d''Arabie'),
  ('Giorgio Armani', 'Armani Privé Rose d''Arabie', 'Armani Privé', 'armani-prive', 'Rose d''Arabie'),
  ('Giorgio Armani', 'Armani Prive Rose d''Arabie', 'Armani Privé', 'armani-prive', 'Rose d''Arabie'),
  ('Giorgio Armani', 'Privé Rose d''Arabie', 'Armani Privé', 'armani-prive', 'Rose d''Arabie'),
  ('Giorgio Armani', 'Prive Rose d''Arabie', 'Armani Privé', 'armani-prive', 'Rose d''Arabie'),
  ('Giorgio Armani', 'Bois d''Encens', 'Armani Privé', 'armani-prive', 'Bois d''Encens'),
  ('Giorgio Armani', 'Armani Privé Bois d''Encens', 'Armani Privé', 'armani-prive', 'Bois d''Encens'),
  ('Giorgio Armani', 'Armani Prive Bois d''Encens', 'Armani Privé', 'armani-prive', 'Bois d''Encens'),
  ('Giorgio Armani', 'Privé Bois d''Encens', 'Armani Privé', 'armani-prive', 'Bois d''Encens'),
  ('Giorgio Armani', 'Prive Bois d''Encens', 'Armani Privé', 'armani-prive', 'Bois d''Encens'),
  ('Giorgio Armani', 'Pierre de Lune', 'Armani Privé', 'armani-prive', 'Pierre de Lune'),
  ('Giorgio Armani', 'Armani Privé Pierre de Lune', 'Armani Privé', 'armani-prive', 'Pierre de Lune'),
  ('Giorgio Armani', 'Armani Prive Pierre de Lune', 'Armani Privé', 'armani-prive', 'Pierre de Lune'),
  ('Giorgio Armani', 'Privé Pierre de Lune', 'Armani Privé', 'armani-prive', 'Pierre de Lune'),
  ('Giorgio Armani', 'Prive Pierre de Lune', 'Armani Privé', 'armani-prive', 'Pierre de Lune'),
  ('Giorgio Armani', 'Ambre Soie', 'Armani Privé', 'armani-prive', 'Ambre Soie'),
  ('Giorgio Armani', 'Armani Privé Ambre Soie', 'Armani Privé', 'armani-prive', 'Ambre Soie'),
  ('Giorgio Armani', 'Armani Prive Ambre Soie', 'Armani Privé', 'armani-prive', 'Ambre Soie'),
  ('Giorgio Armani', 'Privé Ambre Soie', 'Armani Privé', 'armani-prive', 'Ambre Soie'),
  ('Giorgio Armani', 'Prive Ambre Soie', 'Armani Privé', 'armani-prive', 'Ambre Soie'),
  ('Giorgio Armani', 'Cuir Zarzis', 'Armani Privé', 'armani-prive', 'Cuir Zarzis'),
  ('Giorgio Armani', 'Armani Privé Cuir Zarzis', 'Armani Privé', 'armani-prive', 'Cuir Zarzis'),
  ('Giorgio Armani', 'Armani Prive Cuir Zarzis', 'Armani Privé', 'armani-prive', 'Cuir Zarzis'),
  ('Giorgio Armani', 'Privé Cuir Zarzis', 'Armani Privé', 'armani-prive', 'Cuir Zarzis'),
  ('Giorgio Armani', 'Prive Cuir Zarzis', 'Armani Privé', 'armani-prive', 'Cuir Zarzis'),
  ('Giorgio Armani', 'Cuir Améthyste', 'Armani Privé', 'armani-prive', 'Cuir Améthyste'),
  ('Giorgio Armani', 'Armani Privé Cuir Améthyste', 'Armani Privé', 'armani-prive', 'Cuir Améthyste'),
  ('Giorgio Armani', 'Armani Prive Cuir Améthyste', 'Armani Privé', 'armani-prive', 'Cuir Améthyste'),
  ('Giorgio Armani', 'Privé Cuir Améthyste', 'Armani Privé', 'armani-prive', 'Cuir Améthyste'),
  ('Giorgio Armani', 'Prive Cuir Améthyste', 'Armani Privé', 'armani-prive', 'Cuir Améthyste'),
  ('Giorgio Armani', 'Bleu Turquoise', 'Armani Privé', 'armani-prive', 'Bleu Turquoise'),
  ('Giorgio Armani', 'Armani Privé Bleu Turquoise', 'Armani Privé', 'armani-prive', 'Bleu Turquoise'),
  ('Giorgio Armani', 'Armani Prive Bleu Turquoise', 'Armani Privé', 'armani-prive', 'Bleu Turquoise'),
  ('Giorgio Armani', 'Privé Bleu Turquoise', 'Armani Privé', 'armani-prive', 'Bleu Turquoise'),
  ('Giorgio Armani', 'Prive Bleu Turquoise', 'Armani Privé', 'armani-prive', 'Bleu Turquoise'),
  ('Giorgio Armani', 'Vert Malachite', 'Armani Privé', 'armani-prive', 'Vert Malachite'),
  ('Giorgio Armani', 'Armani Privé Vert Malachite', 'Armani Privé', 'armani-prive', 'Vert Malachite'),
  ('Giorgio Armani', 'Armani Prive Vert Malachite', 'Armani Privé', 'armani-prive', 'Vert Malachite'),
  ('Giorgio Armani', 'Privé Vert Malachite', 'Armani Privé', 'armani-prive', 'Vert Malachite'),
  ('Giorgio Armani', 'Prive Vert Malachite', 'Armani Privé', 'armani-prive', 'Vert Malachite'),
  ('Giorgio Armani', 'Rouge Malachite', 'Armani Privé', 'armani-prive', 'Rouge Malachite'),
  ('Giorgio Armani', 'Armani Privé Rouge Malachite', 'Armani Privé', 'armani-prive', 'Rouge Malachite'),
  ('Giorgio Armani', 'Armani Prive Rouge Malachite', 'Armani Privé', 'armani-prive', 'Rouge Malachite'),
  ('Giorgio Armani', 'Privé Rouge Malachite', 'Armani Privé', 'armani-prive', 'Rouge Malachite'),
  ('Giorgio Armani', 'Prive Rouge Malachite', 'Armani Privé', 'armani-prive', 'Rouge Malachite'),
  ('Giorgio Armani', 'Rose Alexandrie', 'Armani Privé', 'armani-prive', 'Rose Alexandrie'),
  ('Giorgio Armani', 'Armani Privé Rose Alexandrie', 'Armani Privé', 'armani-prive', 'Rose Alexandrie'),
  ('Giorgio Armani', 'Armani Prive Rose Alexandrie', 'Armani Privé', 'armani-prive', 'Rose Alexandrie'),
  ('Giorgio Armani', 'Privé Rose Alexandrie', 'Armani Privé', 'armani-prive', 'Rose Alexandrie'),
  ('Giorgio Armani', 'Prive Rose Alexandrie', 'Armani Privé', 'armani-prive', 'Rose Alexandrie'),
  ('Giorgio Armani', 'Rose Milano', 'Armani Privé', 'armani-prive', 'Rose Milano'),
  ('Giorgio Armani', 'Armani Privé Rose Milano', 'Armani Privé', 'armani-prive', 'Rose Milano'),
  ('Giorgio Armani', 'Armani Prive Rose Milano', 'Armani Privé', 'armani-prive', 'Rose Milano'),
  ('Giorgio Armani', 'Privé Rose Milano', 'Armani Privé', 'armani-prive', 'Rose Milano'),
  ('Giorgio Armani', 'Prive Rose Milano', 'Armani Privé', 'armani-prive', 'Rose Milano'),
  ('Giorgio Armani', 'Oranger Alhambra', 'Armani Privé', 'armani-prive', 'Oranger Alhambra'),
  ('Giorgio Armani', 'Armani Privé Oranger Alhambra', 'Armani Privé', 'armani-prive', 'Oranger Alhambra'),
  ('Giorgio Armani', 'Armani Prive Oranger Alhambra', 'Armani Privé', 'armani-prive', 'Oranger Alhambra'),
  ('Giorgio Armani', 'Privé Oranger Alhambra', 'Armani Privé', 'armani-prive', 'Oranger Alhambra'),
  ('Giorgio Armani', 'Prive Oranger Alhambra', 'Armani Privé', 'armani-prive', 'Oranger Alhambra'),
  ('Giorgio Armani', 'Figue Eden', 'Armani Privé', 'armani-prive', 'Figue Eden'),
  ('Giorgio Armani', 'Armani Privé Figue Eden', 'Armani Privé', 'armani-prive', 'Figue Eden'),
  ('Giorgio Armani', 'Armani Prive Figue Eden', 'Armani Privé', 'armani-prive', 'Figue Eden'),
  ('Giorgio Armani', 'Privé Figue Eden', 'Armani Privé', 'armani-prive', 'Figue Eden'),
  ('Giorgio Armani', 'Prive Figue Eden', 'Armani Privé', 'armani-prive', 'Figue Eden'),
  ('Giorgio Armani', 'Eau de Jade', 'Armani Privé', 'armani-prive', 'Eau de Jade'),
  ('Giorgio Armani', 'Armani Privé Eau de Jade', 'Armani Privé', 'armani-prive', 'Eau de Jade'),
  ('Giorgio Armani', 'Armani Prive Eau de Jade', 'Armani Privé', 'armani-prive', 'Eau de Jade'),
  ('Giorgio Armani', 'Privé Eau de Jade', 'Armani Privé', 'armani-prive', 'Eau de Jade'),
  ('Giorgio Armani', 'Prive Eau de Jade', 'Armani Privé', 'armani-prive', 'Eau de Jade'),
  ('Giorgio Armani', 'Jasmin Kaizen', 'Armani Privé', 'armani-prive', 'Jasmin Kaizen'),
  ('Giorgio Armani', 'Armani Privé Jasmin Kaizen', 'Armani Privé', 'armani-prive', 'Jasmin Kaizen'),
  ('Giorgio Armani', 'Armani Prive Jasmin Kaizen', 'Armani Privé', 'armani-prive', 'Jasmin Kaizen'),
  ('Giorgio Armani', 'Privé Jasmin Kaizen', 'Armani Privé', 'armani-prive', 'Jasmin Kaizen'),
  ('Giorgio Armani', 'Prive Jasmin Kaizen', 'Armani Privé', 'armani-prive', 'Jasmin Kaizen'),
  ('Giorgio Armani', 'Néroli Kaizen', 'Armani Privé', 'armani-prive', 'Néroli Kaizen'),
  ('Giorgio Armani', 'Armani Privé Néroli Kaizen', 'Armani Privé', 'armani-prive', 'Néroli Kaizen'),
  ('Giorgio Armani', 'Armani Prive Néroli Kaizen', 'Armani Privé', 'armani-prive', 'Néroli Kaizen'),
  ('Giorgio Armani', 'Privé Néroli Kaizen', 'Armani Privé', 'armani-prive', 'Néroli Kaizen'),
  ('Giorgio Armani', 'Prive Néroli Kaizen', 'Armani Privé', 'armani-prive', 'Néroli Kaizen'),
  ('Giorgio Armani', 'Gardénia Antigua', 'Armani Privé', 'armani-prive', 'Gardénia Antigua'),
  ('Giorgio Armani', 'Armani Privé Gardénia Antigua', 'Armani Privé', 'armani-prive', 'Gardénia Antigua'),
  ('Giorgio Armani', 'Armani Prive Gardénia Antigua', 'Armani Privé', 'armani-prive', 'Gardénia Antigua'),
  ('Giorgio Armani', 'Privé Gardénia Antigua', 'Armani Privé', 'armani-prive', 'Gardénia Antigua'),
  ('Giorgio Armani', 'Prive Gardénia Antigua', 'Armani Privé', 'armani-prive', 'Gardénia Antigua'),
  ('Giorgio Armani', 'Myrrhe Impériale', 'Armani Privé', 'armani-prive', 'Myrrhe Impériale'),
  ('Giorgio Armani', 'Armani Privé Myrrhe Impériale', 'Armani Privé', 'armani-prive', 'Myrrhe Impériale'),
  ('Giorgio Armani', 'Armani Prive Myrrhe Impériale', 'Armani Privé', 'armani-prive', 'Myrrhe Impériale'),
  ('Giorgio Armani', 'Privé Myrrhe Impériale', 'Armani Privé', 'armani-prive', 'Myrrhe Impériale'),
  ('Giorgio Armani', 'Prive Myrrhe Impériale', 'Armani Privé', 'armani-prive', 'Myrrhe Impériale'),
  ('Giorgio Armani', 'Terre d''Ambre', 'Armani Privé', 'armani-prive', 'Terre d''Ambre'),
  ('Giorgio Armani', 'Armani Privé Terre d''Ambre', 'Armani Privé', 'armani-prive', 'Terre d''Ambre'),
  ('Giorgio Armani', 'Armani Prive Terre d''Ambre', 'Armani Privé', 'armani-prive', 'Terre d''Ambre'),
  ('Giorgio Armani', 'Privé Terre d''Ambre', 'Armani Privé', 'armani-prive', 'Terre d''Ambre'),
  ('Giorgio Armani', 'Prive Terre d''Ambre', 'Armani Privé', 'armani-prive', 'Terre d''Ambre'),
  ('Giorgio Armani', 'Vétiver Babylone', 'Armani Privé', 'armani-prive', 'Vétiver Babylone'),
  ('Giorgio Armani', 'Armani Privé Vétiver Babylone', 'Armani Privé', 'armani-prive', 'Vétiver Babylone'),
  ('Giorgio Armani', 'Armani Prive Vétiver Babylone', 'Armani Privé', 'armani-prive', 'Vétiver Babylone'),
  ('Giorgio Armani', 'Privé Vétiver Babylone', 'Armani Privé', 'armani-prive', 'Vétiver Babylone'),
  ('Giorgio Armani', 'Prive Vétiver Babylone', 'Armani Privé', 'armani-prive', 'Vétiver Babylone'),
  ('Giorgio Armani', 'Santal Ocean', 'Armani Privé', 'armani-prive', 'Santal Ocean'),
  ('Giorgio Armani', 'Armani Privé Santal Ocean', 'Armani Privé', 'armani-prive', 'Santal Ocean'),
  ('Giorgio Armani', 'Armani Prive Santal Ocean', 'Armani Privé', 'armani-prive', 'Santal Ocean'),
  ('Giorgio Armani', 'Privé Santal Ocean', 'Armani Privé', 'armani-prive', 'Santal Ocean'),
  ('Giorgio Armani', 'Prive Santal Ocean', 'Armani Privé', 'armani-prive', 'Santal Ocean'),
  ('Giorgio Armani', 'Ambre Orient', 'Armani Privé', 'armani-prive', 'Ambre Orient'),
  ('Giorgio Armani', 'Armani Privé Ambre Orient', 'Armani Privé', 'armani-prive', 'Ambre Orient'),
  ('Giorgio Armani', 'Armani Prive Ambre Orient', 'Armani Privé', 'armani-prive', 'Ambre Orient'),
  ('Giorgio Armani', 'Privé Ambre Orient', 'Armani Privé', 'armani-prive', 'Ambre Orient'),
  ('Giorgio Armani', 'Prive Ambre Orient', 'Armani Privé', 'armani-prive', 'Ambre Orient'),
  ('Giorgio Armani', 'Noir Kogane', 'Armani Privé', 'armani-prive', 'Noir Kogane'),
  ('Giorgio Armani', 'Armani Privé Noir Kogane', 'Armani Privé', 'armani-prive', 'Noir Kogane'),
  ('Giorgio Armani', 'Armani Prive Noir Kogane', 'Armani Privé', 'armani-prive', 'Noir Kogane'),
  ('Giorgio Armani', 'Privé Noir Kogane', 'Armani Privé', 'armani-prive', 'Noir Kogane'),
  ('Giorgio Armani', 'Prive Noir Kogane', 'Armani Privé', 'armani-prive', 'Noir Kogane'),
  ('Giorgio Armani', 'Les Eaux', 'Armani Privé', 'armani-prive', 'Les Eaux'),
  ('Giorgio Armani', 'Armani Privé Les Eaux', 'Armani Privé', 'armani-prive', 'Les Eaux'),
  ('Giorgio Armani', 'Armani Prive Les Eaux', 'Armani Privé', 'armani-prive', 'Les Eaux'),
  ('Giorgio Armani', 'Privé Les Eaux', 'Armani Privé', 'armani-prive', 'Les Eaux'),
  ('Giorgio Armani', 'Prive Les Eaux', 'Armani Privé', 'armani-prive', 'Les Eaux'),
  ('Giorgio Armani', 'Cédre', 'Armani Privé', 'armani-prive', 'Cédre'),
  ('Giorgio Armani', 'Armani Privé Cédre', 'Armani Privé', 'armani-prive', 'Cédre'),
  ('Giorgio Armani', 'Armani Prive Cédre', 'Armani Privé', 'armani-prive', 'Cédre'),
  ('Giorgio Armani', 'Privé Cédre', 'Armani Privé', 'armani-prive', 'Cédre'),
  ('Giorgio Armani', 'Prive Cédre', 'Armani Privé', 'armani-prive', 'Cédre'),
  ('Giorgio Armani', 'Musc Shamal', 'Armani Privé', 'armani-prive', 'Musc Shamal'),
  ('Giorgio Armani', 'Armani Privé Musc Shamal', 'Armani Privé', 'armani-prive', 'Musc Shamal'),
  ('Giorgio Armani', 'Armani Prive Musc Shamal', 'Armani Privé', 'armani-prive', 'Musc Shamal'),
  ('Giorgio Armani', 'Privé Musc Shamal', 'Armani Privé', 'armani-prive', 'Musc Shamal'),
  ('Giorgio Armani', 'Prive Musc Shamal', 'Armani Privé', 'armani-prive', 'Musc Shamal'),
  ('Dior', 'Gris Dior', 'Dior Collection Privée', 'dior-collection-privee', 'Gris Dior'),
  ('Dior', 'La Collection Privée Christian Dior Gris Dior', 'Dior Collection Privée', 'dior-collection-privee', 'Gris Dior'),
  ('Dior', 'La Collection Privée Gris Dior', 'Dior Collection Privée', 'dior-collection-privee', 'Gris Dior'),
  ('Dior', 'Collection Privée Gris Dior', 'Dior Collection Privée', 'dior-collection-privee', 'Gris Dior'),
  ('Dior', 'Dior Collection Privée Gris Dior', 'Dior Collection Privée', 'dior-collection-privee', 'Gris Dior'),
  ('Dior', 'Ambre Nuit', 'Dior Collection Privée', 'dior-collection-privee', 'Ambre Nuit'),
  ('Dior', 'La Collection Privée Christian Dior Ambre Nuit', 'Dior Collection Privée', 'dior-collection-privee', 'Ambre Nuit'),
  ('Dior', 'La Collection Privée Ambre Nuit', 'Dior Collection Privée', 'dior-collection-privee', 'Ambre Nuit'),
  ('Dior', 'Collection Privée Ambre Nuit', 'Dior Collection Privée', 'dior-collection-privee', 'Ambre Nuit'),
  ('Dior', 'Dior Collection Privée Ambre Nuit', 'Dior Collection Privée', 'dior-collection-privee', 'Ambre Nuit'),
  ('Dior', 'Oud Ispahan', 'Dior Collection Privée', 'dior-collection-privee', 'Oud Ispahan'),
  ('Dior', 'La Collection Privée Christian Dior Oud Ispahan', 'Dior Collection Privée', 'dior-collection-privee', 'Oud Ispahan'),
  ('Dior', 'La Collection Privée Oud Ispahan', 'Dior Collection Privée', 'dior-collection-privee', 'Oud Ispahan'),
  ('Dior', 'Collection Privée Oud Ispahan', 'Dior Collection Privée', 'dior-collection-privee', 'Oud Ispahan'),
  ('Dior', 'Dior Collection Privée Oud Ispahan', 'Dior Collection Privée', 'dior-collection-privee', 'Oud Ispahan'),
  ('Dior', 'Rouge Trafalgar', 'Dior Collection Privée', 'dior-collection-privee', 'Rouge Trafalgar'),
  ('Dior', 'La Collection Privée Christian Dior Rouge Trafalgar', 'Dior Collection Privée', 'dior-collection-privee', 'Rouge Trafalgar'),
  ('Dior', 'La Collection Privée Rouge Trafalgar', 'Dior Collection Privée', 'dior-collection-privee', 'Rouge Trafalgar'),
  ('Dior', 'Collection Privée Rouge Trafalgar', 'Dior Collection Privée', 'dior-collection-privee', 'Rouge Trafalgar'),
  ('Dior', 'Dior Collection Privée Rouge Trafalgar', 'Dior Collection Privée', 'dior-collection-privee', 'Rouge Trafalgar'),
  ('Dior', 'Cologne Royale', 'Dior Collection Privée', 'dior-collection-privee', 'Cologne Royale'),
  ('Dior', 'La Collection Privée Christian Dior Cologne Royale', 'Dior Collection Privée', 'dior-collection-privee', 'Cologne Royale'),
  ('Dior', 'La Collection Privée Cologne Royale', 'Dior Collection Privée', 'dior-collection-privee', 'Cologne Royale'),
  ('Dior', 'Collection Privée Cologne Royale', 'Dior Collection Privée', 'dior-collection-privee', 'Cologne Royale'),
  ('Dior', 'Dior Collection Privée Cologne Royale', 'Dior Collection Privée', 'dior-collection-privee', 'Cologne Royale'),
  ('Dior', 'Bois d''Argent', 'Dior Collection Privée', 'dior-collection-privee', 'Bois d''Argent'),
  ('Dior', 'La Collection Privée Christian Dior Bois d''Argent', 'Dior Collection Privée', 'dior-collection-privee', 'Bois d''Argent'),
  ('Dior', 'La Collection Privée Bois d''Argent', 'Dior Collection Privée', 'dior-collection-privee', 'Bois d''Argent'),
  ('Dior', 'Collection Privée Bois d''Argent', 'Dior Collection Privée', 'dior-collection-privee', 'Bois d''Argent'),
  ('Dior', 'Dior Collection Privée Bois d''Argent', 'Dior Collection Privée', 'dior-collection-privee', 'Bois d''Argent'),
  ('Dior', 'Cuir Cannage', 'Dior Collection Privée', 'dior-collection-privee', 'Cuir Cannage'),
  ('Dior', 'La Collection Privée Christian Dior Cuir Cannage', 'Dior Collection Privée', 'dior-collection-privee', 'Cuir Cannage'),
  ('Dior', 'La Collection Privée Cuir Cannage', 'Dior Collection Privée', 'dior-collection-privee', 'Cuir Cannage'),
  ('Dior', 'Collection Privée Cuir Cannage', 'Dior Collection Privée', 'dior-collection-privee', 'Cuir Cannage'),
  ('Dior', 'Dior Collection Privée Cuir Cannage', 'Dior Collection Privée', 'dior-collection-privee', 'Cuir Cannage'),
  ('Dior', 'Eau Noire', 'Dior Collection Privée', 'dior-collection-privee', 'Eau Noire'),
  ('Dior', 'La Collection Privée Christian Dior Eau Noire', 'Dior Collection Privée', 'dior-collection-privee', 'Eau Noire'),
  ('Dior', 'La Collection Privée Eau Noire', 'Dior Collection Privée', 'dior-collection-privee', 'Eau Noire'),
  ('Dior', 'Collection Privée Eau Noire', 'Dior Collection Privée', 'dior-collection-privee', 'Eau Noire'),
  ('Dior', 'Dior Collection Privée Eau Noire', 'Dior Collection Privée', 'dior-collection-privee', 'Eau Noire'),
  ('Dior', 'Granville', 'Dior Collection Privée', 'dior-collection-privee', 'Granville'),
  ('Dior', 'La Collection Privée Christian Dior Granville', 'Dior Collection Privée', 'dior-collection-privee', 'Granville'),
  ('Dior', 'La Collection Privée Granville', 'Dior Collection Privée', 'dior-collection-privee', 'Granville'),
  ('Dior', 'Collection Privée Granville', 'Dior Collection Privée', 'dior-collection-privee', 'Granville'),
  ('Dior', 'Dior Collection Privée Granville', 'Dior Collection Privée', 'dior-collection-privee', 'Granville'),
  ('Dior', 'Mitzah', 'Dior Collection Privée', 'dior-collection-privee', 'Mitzah'),
  ('Dior', 'La Collection Privée Christian Dior Mitzah', 'Dior Collection Privée', 'dior-collection-privee', 'Mitzah'),
  ('Dior', 'La Collection Privée Mitzah', 'Dior Collection Privée', 'dior-collection-privee', 'Mitzah'),
  ('Dior', 'Collection Privée Mitzah', 'Dior Collection Privée', 'dior-collection-privee', 'Mitzah'),
  ('Dior', 'Dior Collection Privée Mitzah', 'Dior Collection Privée', 'dior-collection-privee', 'Mitzah'),
  ('Dior', 'Vétiver', 'Dior Collection Privée', 'dior-collection-privee', 'Vétiver'),
  ('Dior', 'La Collection Privée Christian Dior Vétiver', 'Dior Collection Privée', 'dior-collection-privee', 'Vétiver'),
  ('Dior', 'La Collection Privée Vétiver', 'Dior Collection Privée', 'dior-collection-privee', 'Vétiver'),
  ('Dior', 'Collection Privée Vétiver', 'Dior Collection Privée', 'dior-collection-privee', 'Vétiver'),
  ('Dior', 'Dior Collection Privée Vétiver', 'Dior Collection Privée', 'dior-collection-privee', 'Vétiver'),
  ('Dior', 'New Look 1947', 'Dior Collection Privée', 'dior-collection-privee', 'New Look 1947'),
  ('Dior', 'La Collection Privée Christian Dior New Look 1947', 'Dior Collection Privée', 'dior-collection-privee', 'New Look 1947'),
  ('Dior', 'La Collection Privée New Look 1947', 'Dior Collection Privée', 'dior-collection-privee', 'New Look 1947'),
  ('Dior', 'Collection Privée New Look 1947', 'Dior Collection Privée', 'dior-collection-privee', 'New Look 1947'),
  ('Dior', 'Dior Collection Privée New Look 1947', 'Dior Collection Privée', 'dior-collection-privee', 'New Look 1947'),
  ('Dior', 'Leather Oud', 'Dior Collection Privée', 'dior-collection-privee', 'Leather Oud'),
  ('Dior', 'La Collection Privée Christian Dior Leather Oud', 'Dior Collection Privée', 'dior-collection-privee', 'Leather Oud'),
  ('Dior', 'La Collection Privée Leather Oud', 'Dior Collection Privée', 'dior-collection-privee', 'Leather Oud'),
  ('Dior', 'Collection Privée Leather Oud', 'Dior Collection Privée', 'dior-collection-privee', 'Leather Oud'),
  ('Dior', 'Dior Collection Privée Leather Oud', 'Dior Collection Privée', 'dior-collection-privee', 'Leather Oud'),
  ('Dior', 'Gris Montaigne', 'Dior Collection Privée', 'dior-collection-privee', 'Gris Montaigne'),
  ('Dior', 'La Collection Privée Christian Dior Gris Montaigne', 'Dior Collection Privée', 'dior-collection-privee', 'Gris Montaigne'),
  ('Dior', 'La Collection Privée Gris Montaigne', 'Dior Collection Privée', 'dior-collection-privee', 'Gris Montaigne'),
  ('Dior', 'Collection Privée Gris Montaigne', 'Dior Collection Privée', 'dior-collection-privee', 'Gris Montaigne'),
  ('Dior', 'Dior Collection Privée Gris Montaigne', 'Dior Collection Privée', 'dior-collection-privee', 'Gris Montaigne'),
  ('Dior', 'Balade Sauvage', 'Dior Collection Privée', 'dior-collection-privee', 'Balade Sauvage'),
  ('Dior', 'La Collection Privée Christian Dior Balade Sauvage', 'Dior Collection Privée', 'dior-collection-privee', 'Balade Sauvage'),
  ('Dior', 'La Collection Privée Balade Sauvage', 'Dior Collection Privée', 'dior-collection-privee', 'Balade Sauvage'),
  ('Dior', 'Collection Privée Balade Sauvage', 'Dior Collection Privée', 'dior-collection-privee', 'Balade Sauvage'),
  ('Dior', 'Dior Collection Privée Balade Sauvage', 'Dior Collection Privée', 'dior-collection-privee', 'Balade Sauvage'),
  ('Dior', 'Milly-la-Forêt', 'Dior Collection Privée', 'dior-collection-privee', 'Milly-la-Forêt'),
  ('Dior', 'La Collection Privée Christian Dior Milly-la-Forêt', 'Dior Collection Privée', 'dior-collection-privee', 'Milly-la-Forêt'),
  ('Dior', 'La Collection Privée Milly-la-Forêt', 'Dior Collection Privée', 'dior-collection-privee', 'Milly-la-Forêt'),
  ('Dior', 'Collection Privée Milly-la-Forêt', 'Dior Collection Privée', 'dior-collection-privee', 'Milly-la-Forêt'),
  ('Dior', 'Dior Collection Privée Milly-la-Forêt', 'Dior Collection Privée', 'dior-collection-privee', 'Milly-la-Forêt'),
  ('Dior', 'Patchouli Impérial', 'Dior Collection Privée', 'dior-collection-privee', 'Patchouli Impérial'),
  ('Dior', 'La Collection Privée Christian Dior Patchouli Impérial', 'Dior Collection Privée', 'dior-collection-privee', 'Patchouli Impérial'),
  ('Dior', 'La Collection Privée Patchouli Impérial', 'Dior Collection Privée', 'dior-collection-privee', 'Patchouli Impérial'),
  ('Dior', 'Collection Privée Patchouli Impérial', 'Dior Collection Privée', 'dior-collection-privee', 'Patchouli Impérial'),
  ('Dior', 'Dior Collection Privée Patchouli Impérial', 'Dior Collection Privée', 'dior-collection-privee', 'Patchouli Impérial'),
  ('Dior', 'Poivre Torréfié', 'Dior Collection Privée', 'dior-collection-privee', 'Poivre Torréfié'),
  ('Dior', 'La Collection Privée Christian Dior Poivre Torréfié', 'Dior Collection Privée', 'dior-collection-privee', 'Poivre Torréfié'),
  ('Dior', 'La Collection Privée Poivre Torréfié', 'Dior Collection Privée', 'dior-collection-privee', 'Poivre Torréfié'),
  ('Dior', 'Collection Privée Poivre Torréfié', 'Dior Collection Privée', 'dior-collection-privee', 'Poivre Torréfié'),
  ('Dior', 'Dior Collection Privée Poivre Torréfié', 'Dior Collection Privée', 'dior-collection-privee', 'Poivre Torréfié'),
  ('Dior', 'Jasmin des Anges', 'Dior Collection Privée', 'dior-collection-privee', 'Jasmin des Anges'),
  ('Dior', 'La Collection Privée Christian Dior Jasmin des Anges', 'Dior Collection Privée', 'dior-collection-privee', 'Jasmin des Anges'),
  ('Dior', 'La Collection Privée Jasmin des Anges', 'Dior Collection Privée', 'dior-collection-privee', 'Jasmin des Anges'),
  ('Dior', 'Collection Privée Jasmin des Anges', 'Dior Collection Privée', 'dior-collection-privee', 'Jasmin des Anges'),
  ('Dior', 'Dior Collection Privée Jasmin des Anges', 'Dior Collection Privée', 'dior-collection-privee', 'Jasmin des Anges'),
  ('Dior', 'Fève Délicieuse', 'Dior Collection Privée', 'dior-collection-privee', 'Fève Délicieuse'),
  ('Dior', 'La Collection Privée Christian Dior Fève Délicieuse', 'Dior Collection Privée', 'dior-collection-privee', 'Fève Délicieuse'),
  ('Dior', 'La Collection Privée Fève Délicieuse', 'Dior Collection Privée', 'dior-collection-privee', 'Fève Délicieuse'),
  ('Dior', 'Collection Privée Fève Délicieuse', 'Dior Collection Privée', 'dior-collection-privee', 'Fève Délicieuse'),
  ('Dior', 'Dior Collection Privée Fève Délicieuse', 'Dior Collection Privée', 'dior-collection-privee', 'Fève Délicieuse'),
  ('Dior', 'Cologne Blanche', 'Dior Collection Privée', 'dior-collection-privee', 'Cologne Blanche'),
  ('Dior', 'La Collection Privée Christian Dior Cologne Blanche', 'Dior Collection Privée', 'dior-collection-privee', 'Cologne Blanche'),
  ('Dior', 'La Collection Privée Cologne Blanche', 'Dior Collection Privée', 'dior-collection-privee', 'Cologne Blanche'),
  ('Dior', 'Collection Privée Cologne Blanche', 'Dior Collection Privée', 'dior-collection-privee', 'Cologne Blanche'),
  ('Dior', 'Dior Collection Privée Cologne Blanche', 'Dior Collection Privée', 'dior-collection-privee', 'Cologne Blanche'),
  ('Dior', 'Cologne Forte', 'Dior Collection Privée', 'dior-collection-privee', 'Cologne Forte'),
  ('Dior', 'La Collection Privée Christian Dior Cologne Forte', 'Dior Collection Privée', 'dior-collection-privee', 'Cologne Forte'),
  ('Dior', 'La Collection Privée Cologne Forte', 'Dior Collection Privée', 'dior-collection-privee', 'Cologne Forte'),
  ('Dior', 'Collection Privée Cologne Forte', 'Dior Collection Privée', 'dior-collection-privee', 'Cologne Forte'),
  ('Dior', 'Dior Collection Privée Cologne Forte', 'Dior Collection Privée', 'dior-collection-privee', 'Cologne Forte'),
  ('Tom Ford', 'Neroli Portofino', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Neroli Portofino'),
  ('Tom Ford', 'Private Blend Neroli Portofino', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Neroli Portofino'),
  ('Tom Ford', 'Tom Ford Private Blend Neroli Portofino', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Neroli Portofino'),
  ('Tom Ford', 'Neroli Portofino Acqua', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Neroli Portofino Acqua'),
  ('Tom Ford', 'Private Blend Neroli Portofino Acqua', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Neroli Portofino Acqua'),
  ('Tom Ford', 'Tom Ford Private Blend Neroli Portofino Acqua', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Neroli Portofino Acqua'),
  ('Tom Ford', 'Neroli Portofino Forte', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Neroli Portofino Forte'),
  ('Tom Ford', 'Private Blend Neroli Portofino Forte', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Neroli Portofino Forte'),
  ('Tom Ford', 'Tom Ford Private Blend Neroli Portofino Forte', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Neroli Portofino Forte'),
  ('Tom Ford', 'Soleil Blanc', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Soleil Blanc'),
  ('Tom Ford', 'Private Blend Soleil Blanc', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Soleil Blanc'),
  ('Tom Ford', 'Tom Ford Private Blend Soleil Blanc', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Soleil Blanc'),
  ('Tom Ford', 'Soleil Neige', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Soleil Neige'),
  ('Tom Ford', 'Private Blend Soleil Neige', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Soleil Neige'),
  ('Tom Ford', 'Tom Ford Private Blend Soleil Neige', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Soleil Neige'),
  ('Tom Ford', 'Soleil Brûlant', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Soleil Brûlant'),
  ('Tom Ford', 'Private Blend Soleil Brûlant', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Soleil Brûlant'),
  ('Tom Ford', 'Tom Ford Private Blend Soleil Brûlant', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Soleil Brûlant'),
  ('Tom Ford', 'Soleil de Feu', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Soleil de Feu'),
  ('Tom Ford', 'Private Blend Soleil de Feu', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Soleil de Feu'),
  ('Tom Ford', 'Tom Ford Private Blend Soleil de Feu', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Soleil de Feu'),
  ('Tom Ford', 'Tobacco Vanille', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Tobacco Vanille'),
  ('Tom Ford', 'Private Blend Tobacco Vanille', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Tobacco Vanille'),
  ('Tom Ford', 'Tom Ford Private Blend Tobacco Vanille', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Tobacco Vanille'),
  ('Tom Ford', 'Vanille Fatale', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Vanille Fatale'),
  ('Tom Ford', 'Private Blend Vanille Fatale', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Vanille Fatale'),
  ('Tom Ford', 'Tom Ford Private Blend Vanille Fatale', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Vanille Fatale'),
  ('Tom Ford', 'Bitter Peach', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Bitter Peach'),
  ('Tom Ford', 'Private Blend Bitter Peach', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Bitter Peach'),
  ('Tom Ford', 'Tom Ford Private Blend Bitter Peach', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Bitter Peach'),
  ('Tom Ford', 'Oud Wood', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Oud Wood'),
  ('Tom Ford', 'Private Blend Oud Wood', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Oud Wood'),
  ('Tom Ford', 'Tom Ford Private Blend Oud Wood', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Oud Wood'),
  ('Tom Ford', 'Tuscan Leather', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Tuscan Leather'),
  ('Tom Ford', 'Private Blend Tuscan Leather', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Tuscan Leather'),
  ('Tom Ford', 'Tom Ford Private Blend Tuscan Leather', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Tuscan Leather'),
  ('Tom Ford', 'Fucking Fabulous', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Fucking Fabulous'),
  ('Tom Ford', 'Private Blend Fucking Fabulous', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Fucking Fabulous'),
  ('Tom Ford', 'Tom Ford Private Blend Fucking Fabulous', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Fucking Fabulous'),
  ('Tom Ford', 'Lost Cherry', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Lost Cherry'),
  ('Tom Ford', 'Private Blend Lost Cherry', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Lost Cherry'),
  ('Tom Ford', 'Tom Ford Private Blend Lost Cherry', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Lost Cherry'),
  ('Tom Ford', 'Cherry Smoke', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Cherry Smoke'),
  ('Tom Ford', 'Private Blend Cherry Smoke', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Cherry Smoke'),
  ('Tom Ford', 'Tom Ford Private Blend Cherry Smoke', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Cherry Smoke'),
  ('Tom Ford', 'Electric Cherry', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Electric Cherry'),
  ('Tom Ford', 'Private Blend Electric Cherry', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Electric Cherry'),
  ('Tom Ford', 'Tom Ford Private Blend Electric Cherry', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Electric Cherry'),
  ('Tom Ford', 'Noir de Noir', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Noir de Noir'),
  ('Tom Ford', 'Private Blend Noir de Noir', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Noir de Noir'),
  ('Tom Ford', 'Tom Ford Private Blend Noir de Noir', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Noir de Noir'),
  ('Tom Ford', 'Oud Fleur', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Oud Fleur'),
  ('Tom Ford', 'Private Blend Oud Fleur', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Oud Fleur'),
  ('Tom Ford', 'Tom Ford Private Blend Oud Fleur', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Oud Fleur'),
  ('Tom Ford', 'Rose Prick', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Rose Prick'),
  ('Tom Ford', 'Private Blend Rose Prick', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Rose Prick'),
  ('Tom Ford', 'Tom Ford Private Blend Rose Prick', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Rose Prick'),
  ('Tom Ford', 'Rose de Chine', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Rose de Chine'),
  ('Tom Ford', 'Private Blend Rose de Chine', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Rose de Chine'),
  ('Tom Ford', 'Tom Ford Private Blend Rose de Chine', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Rose de Chine'),
  ('Tom Ford', 'Rive d''Ambre', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Rive d''Ambre'),
  ('Tom Ford', 'Private Blend Rive d''Ambre', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Rive d''Ambre'),
  ('Tom Ford', 'Tom Ford Private Blend Rive d''Ambre', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Rive d''Ambre'),
  ('Tom Ford', 'Costa Azzurra', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Costa Azzurra'),
  ('Tom Ford', 'Private Blend Costa Azzurra', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Costa Azzurra'),
  ('Tom Ford', 'Tom Ford Private Blend Costa Azzurra', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Costa Azzurra'),
  ('Tom Ford', 'Italian Cypress', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Italian Cypress'),
  ('Tom Ford', 'Private Blend Italian Cypress', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Italian Cypress'),
  ('Tom Ford', 'Tom Ford Private Blend Italian Cypress', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Italian Cypress'),
  ('Tom Ford', 'Shanghai Lily', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Shanghai Lily'),
  ('Tom Ford', 'Private Blend Shanghai Lily', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Shanghai Lily'),
  ('Tom Ford', 'Tom Ford Private Blend Shanghai Lily', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Shanghai Lily'),
  ('Tom Ford', 'Jasmin Rouge', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Jasmin Rouge'),
  ('Tom Ford', 'Private Blend Jasmin Rouge', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Jasmin Rouge'),
  ('Tom Ford', 'Tom Ford Private Blend Jasmin Rouge', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Jasmin Rouge'),
  ('Tom Ford', 'White Suede', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'White Suede'),
  ('Tom Ford', 'Private Blend White Suede', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'White Suede'),
  ('Tom Ford', 'Tom Ford Private Blend White Suede', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'White Suede'),
  ('Tom Ford', 'Sole di Positano', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Sole di Positano'),
  ('Tom Ford', 'Private Blend Sole di Positano', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Sole di Positano'),
  ('Tom Ford', 'Tom Ford Private Blend Sole di Positano', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Sole di Positano'),
  ('Tom Ford', 'Vert Bohème', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Vert Bohème'),
  ('Tom Ford', 'Private Blend Vert Bohème', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Vert Bohème'),
  ('Tom Ford', 'Tom Ford Private Blend Vert Bohème', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Vert Bohème'),
  ('Tom Ford', 'Venetian Bergamot', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Venetian Bergamot'),
  ('Tom Ford', 'Private Blend Venetian Bergamot', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Venetian Bergamot'),
  ('Tom Ford', 'Tom Ford Private Blend Venetian Bergamot', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Venetian Bergamot'),
  ('Tom Ford', 'Amber Absolute', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Amber Absolute'),
  ('Tom Ford', 'Private Blend Amber Absolute', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Amber Absolute'),
  ('Tom Ford', 'Tom Ford Private Blend Amber Absolute', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Amber Absolute'),
  ('Tom Ford', 'Plum Japonais', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Plum Japonais'),
  ('Tom Ford', 'Private Blend Plum Japonais', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Plum Japonais'),
  ('Tom Ford', 'Tom Ford Private Blend Plum Japonais', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Plum Japonais'),
  ('Tom Ford', 'Arabian Wood', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Arabian Wood'),
  ('Tom Ford', 'Private Blend Arabian Wood', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Arabian Wood'),
  ('Tom Ford', 'Tom Ford Private Blend Arabian Wood', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Arabian Wood'),
  ('Tom Ford', 'Mandarino di Amalfi', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Mandarino di Amalfi'),
  ('Tom Ford', 'Private Blend Mandarino di Amalfi', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Mandarino di Amalfi'),
  ('Tom Ford', 'Tom Ford Private Blend Mandarino di Amalfi', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Mandarino di Amalfi'),
  ('Tom Ford', 'Santal Blush', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Santal Blush'),
  ('Tom Ford', 'Private Blend Santal Blush', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Santal Blush'),
  ('Tom Ford', 'Tom Ford Private Blend Santal Blush', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Santal Blush'),
  ('Tom Ford', 'Champaca Absolute', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Champaca Absolute'),
  ('Tom Ford', 'Private Blend Champaca Absolute', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Champaca Absolute'),
  ('Tom Ford', 'Tom Ford Private Blend Champaca Absolute', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Champaca Absolute'),
  ('Tom Ford', 'Oud Minérale', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Oud Minérale'),
  ('Tom Ford', 'Private Blend Oud Minérale', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Oud Minérale'),
  ('Tom Ford', 'Tom Ford Private Blend Oud Minérale', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Oud Minérale'),
  ('Tom Ford', 'Bois Marocain', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Bois Marocain'),
  ('Tom Ford', 'Private Blend Bois Marocain', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Bois Marocain'),
  ('Tom Ford', 'Tom Ford Private Blend Bois Marocain', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Bois Marocain'),
  ('Tom Ford', 'Black Violet', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Black Violet'),
  ('Tom Ford', 'Private Blend Black Violet', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Black Violet'),
  ('Tom Ford', 'Tom Ford Private Blend Black Violet', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Black Violet'),
  ('Tom Ford', 'Lavender Extreme', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Lavender Extreme'),
  ('Tom Ford', 'Private Blend Lavender Extreme', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Lavender Extreme'),
  ('Tom Ford', 'Tom Ford Private Blend Lavender Extreme', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Lavender Extreme'),
  ('Tom Ford', 'Ébène Fumé', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Ébène Fumé'),
  ('Tom Ford', 'Private Blend Ébène Fumé', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Ébène Fumé'),
  ('Tom Ford', 'Tom Ford Private Blend Ébène Fumé', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Ébène Fumé'),
  ('Tom Ford', 'Tobacco Oud', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Tobacco Oud'),
  ('Tom Ford', 'Private Blend Tobacco Oud', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Tobacco Oud'),
  ('Tom Ford', 'Tom Ford Private Blend Tobacco Oud', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Tobacco Oud'),
  ('Tom Ford', 'Patchouli Absolu', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Patchouli Absolu'),
  ('Tom Ford', 'Private Blend Patchouli Absolu', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Patchouli Absolu'),
  ('Tom Ford', 'Tom Ford Private Blend Patchouli Absolu', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Patchouli Absolu'),
  ('Tom Ford', 'Purple Patchouli', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Purple Patchouli'),
  ('Tom Ford', 'Private Blend Purple Patchouli', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Purple Patchouli'),
  ('Tom Ford', 'Tom Ford Private Blend Purple Patchouli', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Purple Patchouli'),
  ('Tom Ford', 'Moss Breches', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Moss Breches'),
  ('Tom Ford', 'Private Blend Moss Breches', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Moss Breches'),
  ('Tom Ford', 'Tom Ford Private Blend Moss Breches', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Moss Breches'),
  ('Tom Ford', 'Fleur de Portofino', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Fleur de Portofino'),
  ('Tom Ford', 'Private Blend Fleur de Portofino', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Fleur de Portofino'),
  ('Tom Ford', 'Tom Ford Private Blend Fleur de Portofino', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Fleur de Portofino'),
  ('Tom Ford', 'Sahara Noir', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Sahara Noir'),
  ('Tom Ford', 'Private Blend Sahara Noir', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Sahara Noir'),
  ('Tom Ford', 'Tom Ford Private Blend Sahara Noir', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Sahara Noir'),
  ('Tom Ford', 'Tuscan Leather Intense', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Tuscan Leather Intense'),
  ('Tom Ford', 'Private Blend Tuscan Leather Intense', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Tuscan Leather Intense'),
  ('Tom Ford', 'Tom Ford Private Blend Tuscan Leather Intense', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Tuscan Leather Intense'),
  ('Tom Ford', 'Velvet Gardenia', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Velvet Gardenia'),
  ('Tom Ford', 'Private Blend Velvet Gardenia', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Velvet Gardenia'),
  ('Tom Ford', 'Tom Ford Private Blend Velvet Gardenia', 'Tom Ford Private Blend', 'tom-ford-private-blend', 'Velvet Gardenia'),
  ('Yves Saint Laurent', 'Babycat', 'Yves Saint Laurent Le Vestiaire des Parfums', 'yves-saint-laurent-le-vestiaire-des-parfums', 'Babycat'),
  ('Yves Saint Laurent', 'Le Vestiaire des Parfums Babycat', 'Yves Saint Laurent Le Vestiaire des Parfums', 'yves-saint-laurent-le-vestiaire-des-parfums', 'Babycat'),
  ('Yves Saint Laurent', 'Tuxedo', 'Yves Saint Laurent Le Vestiaire des Parfums', 'yves-saint-laurent-le-vestiaire-des-parfums', 'Tuxedo'),
  ('Yves Saint Laurent', 'Le Vestiaire des Parfums Tuxedo', 'Yves Saint Laurent Le Vestiaire des Parfums', 'yves-saint-laurent-le-vestiaire-des-parfums', 'Tuxedo'),
  ('Yves Saint Laurent', 'Saharienne', 'Yves Saint Laurent Le Vestiaire des Parfums', 'yves-saint-laurent-le-vestiaire-des-parfums', 'Saharienne'),
  ('Yves Saint Laurent', 'Le Vestiaire des Parfums Saharienne', 'Yves Saint Laurent Le Vestiaire des Parfums', 'yves-saint-laurent-le-vestiaire-des-parfums', 'Saharienne'),
  ('Chanel', 'Cuir de Russie', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Cuir de Russie'),
  ('Chanel', 'Les Exclusifs de Chanel Cuir de Russie', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Cuir de Russie'),
  ('Chanel', 'Les Exclusifs Cuir de Russie', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Cuir de Russie'),
  ('Chanel', 'Gardénia', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Gardénia'),
  ('Chanel', 'Les Exclusifs de Chanel Gardénia', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Gardénia'),
  ('Chanel', 'Les Exclusifs Gardénia', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Gardénia'),
  ('Chanel', 'Bois des Îles', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Bois des Îles'),
  ('Chanel', 'Les Exclusifs de Chanel Bois des Îles', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Bois des Îles'),
  ('Chanel', 'Les Exclusifs Bois des Îles', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Bois des Îles'),
  ('Chanel', 'Sycomore', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Sycomore'),
  ('Chanel', 'Les Exclusifs de Chanel Sycomore', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Sycomore'),
  ('Chanel', 'Les Exclusifs Sycomore', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Sycomore'),
  ('Chanel', 'Coromandel', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Coromandel'),
  ('Chanel', 'Les Exclusifs de Chanel Coromandel', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Coromandel'),
  ('Chanel', 'Les Exclusifs Coromandel', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Coromandel'),
  ('Chanel', '31 Rue Cambon', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', '31 Rue Cambon'),
  ('Chanel', 'Les Exclusifs de Chanel 31 Rue Cambon', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', '31 Rue Cambon'),
  ('Chanel', 'Les Exclusifs 31 Rue Cambon', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', '31 Rue Cambon'),
  ('Chanel', 'Jersey', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Jersey'),
  ('Chanel', 'Les Exclusifs de Chanel Jersey', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Jersey'),
  ('Chanel', 'Les Exclusifs Jersey', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Jersey'),
  ('Chanel', 'Misia', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Misia'),
  ('Chanel', 'Les Exclusifs de Chanel Misia', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Misia'),
  ('Chanel', 'Les Exclusifs Misia', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Misia'),
  ('Chanel', 'Beige', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Beige'),
  ('Chanel', 'Les Exclusifs de Chanel Beige', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Beige'),
  ('Chanel', 'Les Exclusifs Beige', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Beige'),
  ('Chanel', 'N°22', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'N°22'),
  ('Chanel', 'Les Exclusifs de Chanel N°22', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'N°22'),
  ('Chanel', 'Les Exclusifs N°22', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'N°22'),
  ('Chanel', 'Bel Respiro', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Bel Respiro'),
  ('Chanel', 'Les Exclusifs de Chanel Bel Respiro', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Bel Respiro'),
  ('Chanel', 'Les Exclusifs Bel Respiro', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Bel Respiro'),
  ('Chanel', 'Eau de Cologne', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Eau de Cologne'),
  ('Chanel', 'Les Exclusifs de Chanel Eau de Cologne', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Eau de Cologne'),
  ('Chanel', 'Les Exclusifs Eau de Cologne', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Eau de Cologne'),
  ('Chanel', 'Paris-Biarritz', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Biarritz'),
  ('Chanel', 'Les Exclusifs de Chanel Paris-Biarritz', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Biarritz'),
  ('Chanel', 'Les Exclusifs Paris-Biarritz', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Biarritz'),
  ('Chanel', 'Paris-Deauville', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Deauville'),
  ('Chanel', 'Les Exclusifs de Chanel Paris-Deauville', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Deauville'),
  ('Chanel', 'Les Exclusifs Paris-Deauville', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Deauville'),
  ('Chanel', 'Paris-Venise', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Venise'),
  ('Chanel', 'Les Exclusifs de Chanel Paris-Venise', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Venise'),
  ('Chanel', 'Les Exclusifs Paris-Venise', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Venise'),
  ('Chanel', 'Paris-Riviera', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Riviera'),
  ('Chanel', 'Les Exclusifs de Chanel Paris-Riviera', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Riviera'),
  ('Chanel', 'Les Exclusifs Paris-Riviera', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Riviera'),
  ('Chanel', 'Paris-Édimbourg', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Édimbourg'),
  ('Chanel', 'Les Exclusifs de Chanel Paris-Édimbourg', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Édimbourg'),
  ('Chanel', 'Les Exclusifs Paris-Édimbourg', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Édimbourg'),
  ('Chanel', 'Paris-Paris', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Paris'),
  ('Chanel', 'Les Exclusifs de Chanel Paris-Paris', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Paris'),
  ('Chanel', 'Les Exclusifs Paris-Paris', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Paris-Paris'),
  ('Chanel', 'La Pausa', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'La Pausa'),
  ('Chanel', 'Les Exclusifs de Chanel La Pausa', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'La Pausa'),
  ('Chanel', 'Les Exclusifs La Pausa', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'La Pausa'),
  ('Chanel', 'Le Lion', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Le Lion'),
  ('Chanel', 'Les Exclusifs de Chanel Le Lion', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Le Lion'),
  ('Chanel', 'Les Exclusifs Le Lion', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', 'Le Lion'),
  ('Chanel', '1932', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', '1932'),
  ('Chanel', 'Les Exclusifs de Chanel 1932', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', '1932'),
  ('Chanel', 'Les Exclusifs 1932', 'Chanel Les Exclusifs', 'chanel-les-exclusifs', '1932'),
  ('Hermès', 'Vétiver Tonka', 'Hermessence', 'hermessence', 'Vétiver Tonka'),
  ('Hermès', 'Hermessence Vétiver Tonka', 'Hermessence', 'hermessence', 'Vétiver Tonka'),
  ('Hermès', 'Ambre Narguilé', 'Hermessence', 'hermessence', 'Ambre Narguilé'),
  ('Hermès', 'Hermessence Ambre Narguilé', 'Hermessence', 'hermessence', 'Ambre Narguilé'),
  ('Hermès', 'Rose Ikebana', 'Hermessence', 'hermessence', 'Rose Ikebana'),
  ('Hermès', 'Hermessence Rose Ikebana', 'Hermessence', 'hermessence', 'Rose Ikebana'),
  ('Hermès', 'Poivre Samarcande', 'Hermessence', 'hermessence', 'Poivre Samarcande'),
  ('Hermès', 'Hermessence Poivre Samarcande', 'Hermessence', 'hermessence', 'Poivre Samarcande'),
  ('Hermès', 'Santal Massoïa', 'Hermessence', 'hermessence', 'Santal Massoïa'),
  ('Hermès', 'Hermessence Santal Massoïa', 'Hermessence', 'hermessence', 'Santal Massoïa'),
  ('Hermès', 'Iris Ukiyoé', 'Hermessence', 'hermessence', 'Iris Ukiyoé'),
  ('Hermès', 'Hermessence Iris Ukiyoé', 'Hermessence', 'hermessence', 'Iris Ukiyoé'),
  ('Hermès', 'Brin de Réglisse', 'Hermessence', 'hermessence', 'Brin de Réglisse'),
  ('Hermès', 'Hermessence Brin de Réglisse', 'Hermessence', 'hermessence', 'Brin de Réglisse'),
  ('Hermès', 'Vanille Galante', 'Hermessence', 'hermessence', 'Vanille Galante'),
  ('Hermès', 'Hermessence Vanille Galante', 'Hermessence', 'hermessence', 'Vanille Galante'),
  ('Hermès', 'Musc Pallida', 'Hermessence', 'hermessence', 'Musc Pallida'),
  ('Hermès', 'Hermessence Musc Pallida', 'Hermessence', 'hermessence', 'Musc Pallida'),
  ('Hermès', 'Cuir d''Ange', 'Hermessence', 'hermessence', 'Cuir d''Ange'),
  ('Hermès', 'Hermessence Cuir d''Ange', 'Hermessence', 'hermessence', 'Cuir d''Ange'),
  ('Hermès', 'Épice Marine', 'Hermessence', 'hermessence', 'Épice Marine'),
  ('Hermès', 'Hermessence Épice Marine', 'Hermessence', 'hermessence', 'Épice Marine'),
  ('Hermès', 'Paprika Brasil', 'Hermessence', 'hermessence', 'Paprika Brasil'),
  ('Hermès', 'Hermessence Paprika Brasil', 'Hermessence', 'hermessence', 'Paprika Brasil'),
  ('Hermès', 'Osmanthe Yunnan', 'Hermessence', 'hermessence', 'Osmanthe Yunnan'),
  ('Hermès', 'Hermessence Osmanthe Yunnan', 'Hermessence', 'hermessence', 'Osmanthe Yunnan'),
  ('Hermès', 'Muguet Porcelaine', 'Hermessence', 'hermessence', 'Muguet Porcelaine'),
  ('Hermès', 'Hermessence Muguet Porcelaine', 'Hermessence', 'hermessence', 'Muguet Porcelaine'),
  ('Hermès', 'Cèdre Sambac', 'Hermessence', 'hermessence', 'Cèdre Sambac'),
  ('Hermès', 'Hermessence Cèdre Sambac', 'Hermessence', 'hermessence', 'Cèdre Sambac'),
  ('Guerlain', 'Angélique Noire', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Angélique Noire'),
  ('Guerlain', 'L''Art & La Matière Angélique Noire', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Angélique Noire'),
  ('Guerlain', 'L''Art et la Matière Angélique Noire', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Angélique Noire'),
  ('Guerlain', 'Bois Mystérieux', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Bois Mystérieux'),
  ('Guerlain', 'L''Art & La Matière Bois Mystérieux', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Bois Mystérieux'),
  ('Guerlain', 'L''Art et la Matière Bois Mystérieux', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Bois Mystérieux'),
  ('Guerlain', 'Cherry Oud', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Cherry Oud'),
  ('Guerlain', 'L''Art & La Matière Cherry Oud', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Cherry Oud'),
  ('Guerlain', 'L''Art et la Matière Cherry Oud', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Cherry Oud'),
  ('Guerlain', 'Cuir Beluga', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Cuir Beluga'),
  ('Guerlain', 'L''Art & La Matière Cuir Beluga', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Cuir Beluga'),
  ('Guerlain', 'L''Art et la Matière Cuir Beluga', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Cuir Beluga'),
  ('Guerlain', 'Encens Mythique d''Orient', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Encens Mythique d''Orient'),
  ('Guerlain', 'L''Art & La Matière Encens Mythique d''Orient', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Encens Mythique d''Orient'),
  ('Guerlain', 'L''Art et la Matière Encens Mythique d''Orient', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Encens Mythique d''Orient'),
  ('Guerlain', 'Gourmand Coquin', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Gourmand Coquin'),
  ('Guerlain', 'L''Art & La Matière Gourmand Coquin', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Gourmand Coquin'),
  ('Guerlain', 'L''Art et la Matière Gourmand Coquin', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Gourmand Coquin'),
  ('Guerlain', 'Iris Torréfié', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Iris Torréfié'),
  ('Guerlain', 'L''Art & La Matière Iris Torréfié', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Iris Torréfié'),
  ('Guerlain', 'L''Art et la Matière Iris Torréfié', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Iris Torréfié'),
  ('Guerlain', 'Mon Exclusif', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Mon Exclusif'),
  ('Guerlain', 'L''Art & La Matière Mon Exclusif', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Mon Exclusif'),
  ('Guerlain', 'L''Art et la Matière Mon Exclusif', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Mon Exclusif'),
  ('Guerlain', 'Néroli Plein Sud', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Néroli Plein Sud'),
  ('Guerlain', 'L''Art & La Matière Néroli Plein Sud', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Néroli Plein Sud'),
  ('Guerlain', 'L''Art et la Matière Néroli Plein Sud', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Néroli Plein Sud'),
  ('Guerlain', 'Oud Essentiel', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Oud Essentiel'),
  ('Guerlain', 'L''Art & La Matière Oud Essentiel', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Oud Essentiel'),
  ('Guerlain', 'L''Art et la Matière Oud Essentiel', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Oud Essentiel'),
  ('Guerlain', 'Patchouli Ardent', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Patchouli Ardent'),
  ('Guerlain', 'L''Art & La Matière Patchouli Ardent', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Patchouli Ardent'),
  ('Guerlain', 'L''Art et la Matière Patchouli Ardent', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Patchouli Ardent'),
  ('Guerlain', 'Rose Barbare', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Rose Barbare'),
  ('Guerlain', 'L''Art & La Matière Rose Barbare', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Rose Barbare'),
  ('Guerlain', 'L''Art et la Matière Rose Barbare', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Rose Barbare'),
  ('Guerlain', 'Rose Nacrée du Désert', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Rose Nacrée du Désert'),
  ('Guerlain', 'L''Art & La Matière Rose Nacrée du Désert', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Rose Nacrée du Désert'),
  ('Guerlain', 'L''Art et la Matière Rose Nacrée du Désert', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Rose Nacrée du Désert'),
  ('Guerlain', 'Santal Royal', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Santal Royal'),
  ('Guerlain', 'L''Art & La Matière Santal Royal', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Santal Royal'),
  ('Guerlain', 'L''Art et la Matière Santal Royal', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Santal Royal'),
  ('Guerlain', 'Spiritueuse Double Vanille', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Spiritueuse Double Vanille'),
  ('Guerlain', 'L''Art & La Matière Spiritueuse Double Vanille', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Spiritueuse Double Vanille'),
  ('Guerlain', 'L''Art et la Matière Spiritueuse Double Vanille', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Spiritueuse Double Vanille'),
  ('Guerlain', 'Tonka Impériale', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Tonka Impériale'),
  ('Guerlain', 'L''Art & La Matière Tonka Impériale', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Tonka Impériale'),
  ('Guerlain', 'L''Art et la Matière Tonka Impériale', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Tonka Impériale'),
  ('Guerlain', 'Vanille Planifolia', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Vanille Planifolia'),
  ('Guerlain', 'L''Art & La Matière Vanille Planifolia', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Vanille Planifolia'),
  ('Guerlain', 'L''Art et la Matière Vanille Planifolia', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Vanille Planifolia'),
  ('Guerlain', 'Cruel Gardénia', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Cruel Gardénia'),
  ('Guerlain', 'L''Art & La Matière Cruel Gardénia', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Cruel Gardénia'),
  ('Guerlain', 'L''Art et la Matière Cruel Gardénia', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Cruel Gardénia'),
  ('Guerlain', 'Vétiver Pour Elle', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Vétiver Pour Elle'),
  ('Guerlain', 'L''Art & La Matière Vétiver Pour Elle', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Vétiver Pour Elle'),
  ('Guerlain', 'L''Art et la Matière Vétiver Pour Elle', 'Guerlain L''Art & La Matière', 'guerlain-l-art-la-matiere', 'Vétiver Pour Elle'),
  ('Prada', 'Purple Rain', 'Prada Olfactories', 'prada-olfactories', 'Purple Rain'),
  ('Prada', 'Olfactories Purple Rain', 'Prada Olfactories', 'prada-olfactories', 'Purple Rain'),
  ('Prada', 'Prada Olfactories Purple Rain', 'Prada Olfactories', 'prada-olfactories', 'Purple Rain'),
  ('Prada', 'Pink Flamingos', 'Prada Olfactories', 'prada-olfactories', 'Pink Flamingos'),
  ('Prada', 'Olfactories Pink Flamingos', 'Prada Olfactories', 'prada-olfactories', 'Pink Flamingos'),
  ('Prada', 'Prada Olfactories Pink Flamingos', 'Prada Olfactories', 'prada-olfactories', 'Pink Flamingos'),
  ('Prada', 'Double Dare', 'Prada Olfactories', 'prada-olfactories', 'Double Dare'),
  ('Prada', 'Olfactories Double Dare', 'Prada Olfactories', 'prada-olfactories', 'Double Dare'),
  ('Prada', 'Prada Olfactories Double Dare', 'Prada Olfactories', 'prada-olfactories', 'Double Dare'),
  ('Prada', 'Un Chant d''Amour', 'Prada Olfactories', 'prada-olfactories', 'Un Chant d''Amour'),
  ('Prada', 'Olfactories Un Chant d''Amour', 'Prada Olfactories', 'prada-olfactories', 'Un Chant d''Amour'),
  ('Prada', 'Prada Olfactories Un Chant d''Amour', 'Prada Olfactories', 'prada-olfactories', 'Un Chant d''Amour'),
  ('Prada', 'Cargo de Nuit', 'Prada Olfactories', 'prada-olfactories', 'Cargo de Nuit'),
  ('Prada', 'Olfactories Cargo de Nuit', 'Prada Olfactories', 'prada-olfactories', 'Cargo de Nuit'),
  ('Prada', 'Prada Olfactories Cargo de Nuit', 'Prada Olfactories', 'prada-olfactories', 'Cargo de Nuit'),
  ('Prada', 'Nue au Soleil', 'Prada Olfactories', 'prada-olfactories', 'Nue au Soleil'),
  ('Prada', 'Olfactories Nue au Soleil', 'Prada Olfactories', 'prada-olfactories', 'Nue au Soleil'),
  ('Prada', 'Prada Olfactories Nue au Soleil', 'Prada Olfactories', 'prada-olfactories', 'Nue au Soleil'),
  ('Prada', 'Tainted Love', 'Prada Olfactories', 'prada-olfactories', 'Tainted Love'),
  ('Prada', 'Olfactories Tainted Love', 'Prada Olfactories', 'prada-olfactories', 'Tainted Love'),
  ('Prada', 'Prada Olfactories Tainted Love', 'Prada Olfactories', 'prada-olfactories', 'Tainted Love'),
  ('Prada', 'Heat Wave', 'Prada Olfactories', 'prada-olfactories', 'Heat Wave'),
  ('Prada', 'Olfactories Heat Wave', 'Prada Olfactories', 'prada-olfactories', 'Heat Wave'),
  ('Prada', 'Prada Olfactories Heat Wave', 'Prada Olfactories', 'prada-olfactories', 'Heat Wave'),
  ('Prada', 'Marienbad', 'Prada Olfactories', 'prada-olfactories', 'Marienbad'),
  ('Prada', 'Olfactories Marienbad', 'Prada Olfactories', 'prada-olfactories', 'Marienbad'),
  ('Prada', 'Prada Olfactories Marienbad', 'Prada Olfactories', 'prada-olfactories', 'Marienbad'),
  ('Prada', 'Day for Night', 'Prada Olfactories', 'prada-olfactories', 'Day for Night'),
  ('Prada', 'Olfactories Day for Night', 'Prada Olfactories', 'prada-olfactories', 'Day for Night'),
  ('Prada', 'Prada Olfactories Day for Night', 'Prada Olfactories', 'prada-olfactories', 'Day for Night'),
  ('Prada', 'Dark Light', 'Prada Olfactories', 'prada-olfactories', 'Dark Light'),
  ('Prada', 'Olfactories Dark Light', 'Prada Olfactories', 'prada-olfactories', 'Dark Light'),
  ('Prada', 'Prada Olfactories Dark Light', 'Prada Olfactories', 'prada-olfactories', 'Dark Light'),
  ('Prada', 'Soleil au Zénith', 'Prada Olfactories', 'prada-olfactories', 'Soleil au Zénith'),
  ('Prada', 'Olfactories Soleil au Zénith', 'Prada Olfactories', 'prada-olfactories', 'Soleil au Zénith'),
  ('Prada', 'Prada Olfactories Soleil au Zénith', 'Prada Olfactories', 'prada-olfactories', 'Soleil au Zénith'),
  ('Prada', 'Miracle of the Rose', 'Prada Olfactories', 'prada-olfactories', 'Miracle of the Rose'),
  ('Prada', 'Olfactories Miracle of the Rose', 'Prada Olfactories', 'prada-olfactories', 'Miracle of the Rose'),
  ('Prada', 'Prada Olfactories Miracle of the Rose', 'Prada Olfactories', 'prada-olfactories', 'Miracle of the Rose'),
  ('Prada', 'Midnight Train', 'Prada Olfactories', 'prada-olfactories', 'Midnight Train'),
  ('Prada', 'Olfactories Midnight Train', 'Prada Olfactories', 'prada-olfactories', 'Midnight Train'),
  ('Prada', 'Prada Olfactories Midnight Train', 'Prada Olfactories', 'prada-olfactories', 'Midnight Train'),
  ('Prada', 'Troubled Midnight', 'Prada Olfactories', 'prada-olfactories', 'Troubled Midnight'),
  ('Prada', 'Olfactories Troubled Midnight', 'Prada Olfactories', 'prada-olfactories', 'Troubled Midnight'),
  ('Prada', 'Prada Olfactories Troubled Midnight', 'Prada Olfactories', 'prada-olfactories', 'Troubled Midnight'),
  ('Prada', 'Malombra', 'Prada Olfactories', 'prada-olfactories', 'Malombra'),
  ('Prada', 'Olfactories Malombra', 'Prada Olfactories', 'prada-olfactories', 'Malombra'),
  ('Prada', 'Prada Olfactories Malombra', 'Prada Olfactories', 'prada-olfactories', 'Malombra'),
  ('Prada', 'Some Velvet Morning', 'Prada Olfactories', 'prada-olfactories', 'Some Velvet Morning'),
  ('Prada', 'Olfactories Some Velvet Morning', 'Prada Olfactories', 'prada-olfactories', 'Some Velvet Morning'),
  ('Prada', 'Prada Olfactories Some Velvet Morning', 'Prada Olfactories', 'prada-olfactories', 'Some Velvet Morning'),
  ('Prada', 'Desert Serenade', 'Prada Olfactories', 'prada-olfactories', 'Desert Serenade'),
  ('Prada', 'Olfactories Desert Serenade', 'Prada Olfactories', 'prada-olfactories', 'Desert Serenade'),
  ('Prada', 'Prada Olfactories Desert Serenade', 'Prada Olfactories', 'prada-olfactories', 'Desert Serenade'),
  ('Prada', 'Babylon', 'Prada Olfactories', 'prada-olfactories', 'Babylon'),
  ('Prada', 'Olfactories Babylon', 'Prada Olfactories', 'prada-olfactories', 'Babylon'),
  ('Prada', 'Prada Olfactories Babylon', 'Prada Olfactories', 'prada-olfactories', 'Babylon'),
  ('Prada', 'Moonlight Shadow', 'Prada Olfactories', 'prada-olfactories', 'Moonlight Shadow'),
  ('Prada', 'Olfactories Moonlight Shadow', 'Prada Olfactories', 'prada-olfactories', 'Moonlight Shadow'),
  ('Prada', 'Prada Olfactories Moonlight Shadow', 'Prada Olfactories', 'prada-olfactories', 'Moonlight Shadow'),
  ('Cartier', 'La Treizième Heure', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'La Treizième Heure'),
  ('Cartier', 'Les Heures de Parfum La Treizième Heure', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'La Treizième Heure'),
  ('Cartier', 'L''Heure Folle', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Folle'),
  ('Cartier', 'Les Heures de Parfum L''Heure Folle', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Folle'),
  ('Cartier', 'L''Heure Défendue', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Défendue'),
  ('Cartier', 'Les Heures de Parfum L''Heure Défendue', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Défendue'),
  ('Cartier', 'L''Heure Mystérieuse', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Mystérieuse'),
  ('Cartier', 'Les Heures de Parfum L''Heure Mystérieuse', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Mystérieuse'),
  ('Cartier', 'L''Heure Brillante', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Brillante'),
  ('Cartier', 'Les Heures de Parfum L''Heure Brillante', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Brillante'),
  ('Cartier', 'L''Heure Fougueuse', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Fougueuse'),
  ('Cartier', 'Les Heures de Parfum L''Heure Fougueuse', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Fougueuse'),
  ('Cartier', 'L''Heure Convoitée', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Convoitée'),
  ('Cartier', 'Les Heures de Parfum L''Heure Convoitée', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Convoitée'),
  ('Cartier', 'L''Heure Vertueuse', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Vertueuse'),
  ('Cartier', 'Les Heures de Parfum L''Heure Vertueuse', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Vertueuse'),
  ('Cartier', 'L''Heure Perdue', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Perdue'),
  ('Cartier', 'Les Heures de Parfum L''Heure Perdue', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'L''Heure Perdue'),
  ('Cartier', 'La Douzième Heure', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'La Douzième Heure'),
  ('Cartier', 'Les Heures de Parfum La Douzième Heure', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'La Douzième Heure'),
  ('Cartier', 'La Onzième Heure', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'La Onzième Heure'),
  ('Cartier', 'Les Heures de Parfum La Onzième Heure', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'La Onzième Heure'),
  ('Cartier', 'La Dixième Heure', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'La Dixième Heure'),
  ('Cartier', 'Les Heures de Parfum La Dixième Heure', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'La Dixième Heure'),
  ('Cartier', 'La Neuvième Heure', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'La Neuvième Heure'),
  ('Cartier', 'Les Heures de Parfum La Neuvième Heure', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'La Neuvième Heure'),
  ('Cartier', 'La Huitième Heure', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'La Huitième Heure'),
  ('Cartier', 'Les Heures de Parfum La Huitième Heure', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'La Huitième Heure'),
  ('Cartier', 'Oud & Santal', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'Oud & Santal'),
  ('Cartier', 'Les Heures de Parfum Oud & Santal', 'Cartier Les Heures de Parfum', 'cartier-les-heures-de-parfum', 'Oud & Santal'),
  ('Hugo Boss', 'Man', 'Hugo', 'hugo', 'Man'),
  ('Hugo Boss', 'Hugo Man', 'Hugo', 'hugo', 'Man'),
  ('Hugo Boss', 'Woman', 'Hugo', 'hugo', 'Woman'),
  ('Hugo Boss', 'Hugo Woman', 'Hugo', 'hugo', 'Woman'),
  ('Hugo Boss', 'Just Different', 'Hugo', 'hugo', 'Just Different'),
  ('Hugo Boss', 'Hugo Just Different', 'Hugo', 'hugo', 'Just Different'),
  ('Hugo Boss', 'Element', 'Hugo', 'hugo', 'Element'),
  ('Hugo Boss', 'Hugo Element', 'Hugo', 'hugo', 'Element'),
  ('Hugo Boss', 'Energise', 'Hugo', 'hugo', 'Energise'),
  ('Hugo Boss', 'Hugo Energise', 'Hugo', 'hugo', 'Energise'),
  ('Hugo Boss', 'Reversed', 'Hugo', 'hugo', 'Reversed'),
  ('Hugo Boss', 'Hugo Reversed', 'Hugo', 'hugo', 'Reversed'),
  ('Hugo Boss', 'Iced', 'Hugo', 'hugo', 'Iced'),
  ('Hugo Boss', 'Hugo Iced', 'Hugo', 'hugo', 'Iced'),
  ('Hugo Boss', 'Deep Red', 'Hugo', 'hugo', 'Deep Red'),
  ('Hugo Boss', 'Hugo Deep Red', 'Hugo', 'hugo', 'Deep Red'),
  ('Hugo Boss', 'Dark Blue', 'Hugo', 'hugo', 'Dark Blue'),
  ('Hugo Boss', 'Hugo Dark Blue', 'Hugo', 'hugo', 'Dark Blue'),
  ('Hugo Boss', 'Extreme', 'Hugo', 'hugo', 'Extreme'),
  ('Hugo Boss', 'Hugo Extreme', 'Hugo', 'hugo', 'Extreme'),
  ('Hugo Boss', 'Red', 'Hugo', 'hugo', 'Red'),
  ('Hugo Boss', 'Hugo Red', 'Hugo', 'hugo', 'Red');

-- 1. Lignes manquantes, seulement si un parfum doit y entrer.
INSERT INTO "Brand" (id, name, slug, "catalogMode", status, "updatedAt")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || x.marque_cible), 1, 24),
       x.marque_cible, x.slug_cible, 'CURATED', 'PUBLISHED', now()
FROM (
  SELECT DISTINCT d.marque_cible, d.slug_cible
  FROM _deplacements d
  JOIN "Brand"   bs ON lower(btrim(bs.name)) = lower(d.marque_source)
  JOIN "Perfume" p  ON p."brandId" = bs.id AND lower(btrim(p.name)) = lower(d.parfum_source)
) x
WHERE NOT EXISTS (SELECT 1 FROM "Brand" b WHERE lower(btrim(b.name)) = lower(x.marque_cible))
  AND NOT EXISTS (SELECT 1 FROM "Brand" b WHERE b.slug = x.slug_cible);

-- 2. Déplacement. Un parfum ne vise qu'une cible ; une cible (ligne, nom) ne reçoit qu'un parfum ;
--    un nom déjà présent dans la ligne n'est jamais doublé (contrainte unique brandId + name).
WITH candidats AS (
  SELECT DISTINCT ON (p.id) p.id AS perfume_id, bc.id AS cible_id, d.nom_cible
  FROM _deplacements d
  JOIN "Brand"   bs ON lower(btrim(bs.name)) = lower(d.marque_source)
  JOIN "Brand"   bc ON lower(btrim(bc.name)) = lower(d.marque_cible)
  JOIN "Perfume" p  ON p."brandId" = bs.id AND lower(btrim(p.name)) = lower(d.parfum_source)
  WHERE bc.id <> bs.id
  ORDER BY p.id, length(d.parfum_source) DESC
), retenus AS (
  SELECT DISTINCT ON (c.cible_id, lower(c.nom_cible)) c.*
  FROM candidats c
  WHERE NOT EXISTS (
    SELECT 1 FROM "Perfume" q WHERE q."brandId" = c.cible_id AND lower(q.name) = lower(c.nom_cible)
  )
  ORDER BY c.cible_id, lower(c.nom_cible), c.perfume_id
)
UPDATE "Perfume" p
SET "brandId"   = r.cible_id,
    name        = r.nom_cible,
    "updatedAt" = now()
FROM retenus r
WHERE p.id = r.perfume_id;

DROP TABLE _deplacements;

COMMIT;
