// Compositions (docs/refonte/05-DESIGN-SYSTEM.md §3.2).
export { PageScaffold } from "./PageScaffold";
export { SectionHeader } from "./SectionHeader";
export { ListSection } from "./ListSection";
export { KpiTile } from "./KpiTile";
export { BarChart, BarChartSkeleton } from "./BarChart";
export type { BarPoint } from "./bar-chart-model";
export { Money, type MoneyTone } from "./Money";
export type { MoneyValue } from "./money-value";
export { FormField, type FieldControlProps } from "./FormField";
export { FormSection } from "./FormSection";
export { CollapsibleSection } from "./CollapsibleSection";
export { SelectSheet, type SelectOption, type SelectCreateContext } from "./SelectSheet";
export { ConfirmDialog } from "./ConfirmDialog";
export { ErrorBanner } from "./ErrorBanner";
export { InlineNameEditor } from "./InlineNameEditor";
export { ImageField, type ImageKind, type ImageCrop } from "./ImageField";
export { ImagePreview, type ImageFrame } from "./ImagePreview";
export { MediaGallery, saveMedia, SAVE_FAILED_MESSAGE, type MediaItem, type SaveOutcome } from "./MediaGallery";
export { DateLabel } from "./DateLabel";
export { RelativeTime } from "./RelativeTime";
export type { DateFormat } from "./date-format";
export { ShareButton, type SharePayload } from "./ShareButton";
export { GiftToggle } from "./GiftToggle";
