import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "1.25rem",
      screens: { "2xl": "1200px" },
    },
    extend: {
      colors: {
        nurea: {
          bg: "var(--nurea-bg)",
          surface: "var(--nurea-surface)",
          "surface-hover": "var(--nurea-surface-hover)",
          accent: "var(--nurea-accent)",
          "accent-hover": "var(--nurea-accent-hover)",
          "accent-subtle": "var(--nurea-accent-subtle)",
          text: "var(--nurea-text)",
          muted: "var(--nurea-text-muted)",
          subtle: "var(--nurea-text-subtle)",
          cuivre: "var(--nurea-cuivre)",
          border: "var(--nurea-border)",
          "border-hover": "var(--nurea-border-hover)",
          glow: "var(--nurea-glow)",
          success: "var(--nurea-success)",
          "success-subtle": "var(--nurea-success-subtle)",
          "success-border": "var(--nurea-success-border)",
          warning: "var(--nurea-warning)",
          "warning-subtle": "var(--nurea-warning-subtle)",
          "warning-border": "var(--nurea-warning-border)",
          danger: "var(--nurea-danger)",
          "danger-subtle": "var(--nurea-danger-subtle)",
          "danger-border": "var(--nurea-danger-border)",
          info: "var(--nurea-info)",
          "info-subtle": "var(--nurea-info-subtle)",
          "info-border": "var(--nurea-info-border)",
        },
        admin: {
          bg: "var(--admin-bg)",
          surface: "var(--admin-surface)",
          "surface-muted": "var(--admin-surface-muted)",
          "surface-hover": "var(--admin-surface-hover)",
          text: "var(--admin-text)",
          muted: "var(--admin-text-muted)",
          subtle: "var(--admin-text-subtle)",
          border: "var(--admin-border)",
          "border-hover": "var(--admin-border-hover)",
          accent: "var(--admin-accent)",
          "accent-hover": "var(--admin-accent-hover)",
          "accent-subtle": "var(--admin-accent-subtle)",
          "accent-ring": "var(--admin-accent-ring)",
          cuivre: "var(--admin-cuivre)",
          "cuivre-subtle": "var(--admin-cuivre-subtle)",
          success: "var(--admin-success)",
          "success-subtle": "var(--admin-success-subtle)",
          "success-border": "var(--admin-success-border)",
          warning: "var(--admin-warning)",
          "warning-subtle": "var(--admin-warning-subtle)",
          "warning-border": "var(--admin-warning-border)",
          danger: "var(--admin-danger)",
          "danger-subtle": "var(--admin-danger-subtle)",
          "danger-border": "var(--admin-danger-border)",
          info: "var(--admin-info)",
          "info-subtle": "var(--admin-info-subtle)",
          "info-border": "var(--admin-info-border)",
        },
      },
      boxShadow: {
        "admin-sm": "var(--admin-shadow-sm)",
        "admin-md": "var(--admin-shadow-md)",
        "admin-lg": "var(--admin-shadow-lg)",
        "admin-xl": "var(--admin-shadow-xl)",
      },
      fontFamily: {
        serif: ["var(--font-serif)", "Georgia", "serif"],
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
      },
      borderRadius: {
        lg: "0px",
        md: "2px",
        sm: "2px",
      },
      transitionTimingFunction: {
        "out-expo": "cubic-bezier(0.16, 1, 0.3, 1)",
      },
      letterSpacing: {
        "nurea-tight": "var(--nurea-tracking-tight)",
        "nurea-label": "var(--nurea-tracking-label)",
        "nurea-wide": "var(--nurea-tracking-wide)",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
